name: fitsio-dev
channels:
  - conda-forge
dependencies:
  - python >=3.10
  - numpy >=1.7
  - pip
  - setuptools
  - setuptools-scm >=8
  - wget
  - make
  - pytest
  - pytest-run-parallel
  - pytest-skip-slow
