exclude = [
    ".git",
    "build",
    "dist",
    "cfitsio-*",
    "patches",
    "zlib",
    ".github",
]
line-length = 79

[lint]
select = ["E", "F", "W"]
preview = true

[format]
quote-style = "preserve"
