name: lint

on:
  push:
    branches:
      - master
  pull_request: null

env:
  PY_COLORS: "1"

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: mamba-org/setup-micromamba@ce51e99f4bb8a82ab7158c4dc59ef4634c59c4f9  #v3.1.0
        with:
          environment-name: fitsio-dev
          condarc: |
            channels:
            - conda-forge
            show_channel_urls: true
            channel_priority: strict
            always_yes: true
          create-args: >-
            pre-commit
            identify>2.6

      - name: pre-commit
        run: |
          pre-commit run -a
