name: lint

on:
  push:
    branches:
      - master
  pull_request: null

env:
  PY_COLORS: "1"

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476  #v3.0.0
        with:
          environment-name: fitsio-dev
          condarc: |
            channels:
            - conda-forge
            show_channel_urls: true
            channel_priority: strict
            always_yes: true
          create-args: >-
            pre-commit
            identify>2.6

      - name: pre-commit
        run: |
          pre-commit run -a
